version: '3.9'

services:
  postgres:
    image: 'postgres:13.2-alpine'
    environment:
      POSTGRES_PASSWORD: 'postgres_dev'
      POSTGRES_USER: 'postgres_dev'
      POSTGRES_DB: 'postgres_dev'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:6.2.1-alpine'

    ports:
      - '6379:6379'
